import type { Concept, Difficulty, Question } from "./data";

export type Lesson1SourcePage = { page:number; module:string; extractedText:string; visualDescription:string };
const module="Introduction to Remote Sensing";
const c=(id:string,term:string,definition:string,sourcePage:number,facts:string[]=[],difficulty:Difficulty="medium"):Concept=>({id:`l1-${id}`,module,topic:module,term,definition,facts,sourcePage,difficulty,tags:["Lesson 1",module,term]});
const q=(id:string,type:Question["type"],question:string,answer:string,sourcePage:number,explanation:string,choices?:string[],difficulty:Difficulty="medium"):Question=>({id:`l1-${id}`,type,question,answer,sourcePage,module,explanation,choices,difficulty});

export const lesson1Concepts:Concept[]=[
 c("definition","Remote sensing","The science and art of obtaining information about an object, area, or phenomenon from data acquired by a device not in contact with it.",4,["It commonly uses electromagnetic techniques to study Earth's surface and atmosphere."],"easy"),
 c("rs-gis","Remote sensing and GIS","Remote sensing collects spatial data at a distance, while GIS stores, analyzes, and visualizes that data.",8,["Example: remote sensing captures forest-cover imagery; GIS maps deforestation from it."],"easy"),
 c("emr","Electromagnetic radiation","A way energy travels through space; sunlight, heat from fire, X-rays, and microwave energy are all forms of EMR.",12,["These forms share wavelike properties."],"easy"),
 c("scope","Scope of remote sensing","In a restricted sense, remote sensing acquires land, ocean, and atmospheric information from airborne or spaceborne sensors.",14,["Platforms include aircraft, balloons, satellites, and space shuttles."],"medium"),
 c("method-choice","When to use remote sensing","Use remote sensing when it provides information that is reliable, cost-effective, or new but necessary.",16,["The lesson asks whether RS is the best available method for acquiring the information."],"medium"),
 c("record","Remote-sensing record","Remotely sensed data records an entire area at a point in time and can provide relatively consistent spatial and temporal information.",18,["It does not interfere with the resources being observed and can directly or indirectly describe environmental characteristics."],"medium"),
 c("energy-source","Energy source","Remote sensing begins with energy radiating from a source.",19,["Passive sources occur naturally, such as the Sun. Active sources can be lamps, lasers, or microwave transmitters."],"easy"),
 c("rs-process","Remote-sensing process","Energy reaches an object, interacts with matter, and part of it reflects toward a sensor on a platform.",20,["The sensor quantizes and stores incoming-radiation intensity; stored values become images that can be processed and analyzed."],"medium"),
 c("passive-system","Passive system","A passive system detects naturally occurring radiation, including solar radiation reflected from objects and thermal radiation emitted by objects.",22,[],"easy"),
 c("active-system","Active system","An active system emits radiation and analyzes the return signal.",23,["In principle it can use any EMR, but atmospheric transparency limits practical operation."],"easy"),
 c("advantages","Advantages of remote sensing","Remote sensing reduces sampling bias, is unobstructive, and rapidly gathers data across large areas or atmospheric volumes.",24,["It can observe hard-to-reach, slow, expensive, dangerous, or politically inconvenient locations. Most systems generate calibrated digital data for computer analysis."],"medium"),
 c("limitations","Limitations of remote sensing","Remote sensing does not solve every information problem and can involve human-method error, instrument calibration drift, and costly collection or interpretation.",25,[],"medium"),
 c("applications","Applications of remote sensing","Applications in the deck include land use and cover, air and water quality, resource monitoring, urban heat, land conversion, and topographic studies.",26,[],"easy"),
 c("arcmap","ArcMap","A central ArcGIS Desktop application for exploring GIS datasets, assigning symbols, creating maps, layouts, and editing datasets.",27,["The lesson describes maps as collections of layers and elements such as scale bars, north arrows, titles, and legends."],"medium"),
 c("esri","ESRI and ArcGIS","Environmental Systems Research Institute (ESRI) is a GIS software company best known for ArcGIS products across desktop, server, and mobile platforms.",29,["The lesson identifies the headquarters as Redlands, California."],"medium"),
 c("arcmap-support","ArcMap support transition","The deck states that ArcMap support ends after March 1, 2026 and encourages transition to ArcGIS Pro.",31,["This is retained as a source-deck statement."],"medium")
];

export const lesson1Questions:Question[]=[
 q("q1","identify","Obtaining information about an object without physical contact is…","Remote sensing",4,"The deck defines remote sensing as non-contact information acquisition."),
 q("q2","mcq","Which tool stores, analyzes, and visualizes spatial data?","GIS",8,"GIS analyzes and visualizes data; remote sensing collects it.",["GIS","Remote sensing","A satellite sensor","A laser"]),
 q("q3","tf","Remote sensing can capture forest-cover imagery while GIS maps deforestation from that imagery.","true",8,"This is the example used in the deck."),
 q("q4","mcq","Which is a form of electromagnetic radiation?","X-rays",12,"The deck lists sunlight, fire heat, X-rays, and microwave cooking energy as EMR.",["X-rays","Sound waves only","Soil texture","Political boundaries"]),
 q("q5","identify","Sensors carried by aircraft or balloons are described as…","Airborne",14,"The deck distinguishes airborne platforms from spaceborne platforms."),
 q("q6","tf","Remote sensing should be selected even when it is not reliable for the application.","false",16,"The deck says it should provide reliable information for the application."),
 q("q7","mcq","Which source is naturally available for passive remote sensing?","The Sun",19,"The Sun is identified as a passive energy source.",["The Sun","A laser","A microwave transmitter","A lamp"]),
 q("q8","identify","After the sensor quantizes and stores incoming radiation, the values are transformed into…","Images",21,"The deck says stored energy values become images before analysis."),
 q("q9","identify","A system that detects naturally occurring radiation is a…","Passive system",22,"Passive systems detect reflected solar and emitted thermal radiation."),
 q("q10","identify","A system that emits radiation and analyzes what returns is an…","Active system",23,"Active systems provide their own radiation source."),
 q("q11","mcq","Which is an advantage of remote sensing?","It can observe difficult or dangerous locations",24,"Airborne and spaceborne systems can gather data where on-site measurement is difficult, slow, expensive, dangerous, or inconvenient.",["It can observe difficult or dangerous locations","It removes every error","It never needs interpretation","It only covers small areas"]),
 q("q12","tf","Instrument calibration can change over time and limit remote-sensing data.","true",25,"The deck lists instruments becoming uncalibrated through time as a limitation."),
 q("q13","identify","Mapping land use, land cover, and urban heat are examples of…","Applications of remote sensing",26,"These are included in the applications slide."),
 q("q14","identify","The ArcGIS Desktop application used to display and explore GIS datasets is…","ArcMap",27,"The deck identifies ArcMap as a central ArcGIS Desktop application."),
 q("q15","mcq","Which company is best known for ArcGIS products?","ESRI",29,"ESRI stands for Environmental Systems Research Institute.",["ESRI","NASA","USGS","NOAA"]),
 q("q16","number","According to the source deck, ArcMap support ends after March 1, ___.","2026",31,"The deck states that ArcMap would no longer be supported after March 1, 2026."),
 q("q17","tf","Remote sensing necessarily interferes with the resource being observed.","false",18,"The deck identifies non-interference as a strength of remote sensing."),
 q("q18","classify","A laser used to illuminate a target is an example of a ___ energy source.","Active",19,"A lamp, laser, or microwave transmitter can provide active energy.")
 ,q("q19","tf","Remote sensing is commonly used to study Earth's surface and atmosphere with electromagnetic techniques.","true",4,"The definition slide connects remote sensing to electromagnetic techniques.")
 ,q("q20","identify","Data acquisition from a satellite is described as…","Spaceborne",14,"The deck distinguishes spaceborne platforms from airborne ones.")
 ,q("q21","mcq","Which statement supports using remote sensing?","It provides information that is cost-effective",16,"Cost-effectiveness is one of the stated decision criteria.",["It provides information that is cost-effective","It always replaces fieldwork","It never needs a sensor","It only works for cities"])
 ,q("q22","tf","A remotely sensed record can describe an entire area at a point in time.","true",18,"The deck notes its broad, time-specific area coverage.")
 ,q("q23","identify","Natural solar energy reflected from an object is detected by a…","Passive system",22,"Passive systems detect naturally occurring radiation.")
 ,q("q24","mcq","Which energy source is active?","Microwave transmitter",19,"Microwave transmitters are listed among active sources.",["Microwave transmitter","The Sun","Natural thermal emission","Reflected daylight"])
 ,q("q25","tf","An active system may be limited by atmospheric transparency.","true",23,"Atmospheric transparency limits practical active-system operation.")
 ,q("q26","identify","The step that turns incoming-radiation intensity into stored values is…","Quantization",20,"The sensor quantizes and stores the intensity.")
 ,q("q27","mcq","Which is NOT presented as an advantage of remote sensing?","It eliminates all human-method error",25,"Human-method error is listed among limitations.",["It eliminates all human-method error","It reduces sampling bias","It can cover large areas rapidly","It can observe difficult locations"])
 ,q("q28","tf","Most remote-sensing systems produce digital data that can be analyzed by computer.","true",24,"Calibrated digital data is a stated advantage.")
 ,q("q29","identify","Mapping air and water quality is an application of…","Remote sensing",26,"The applications slide includes air and water quality.")
 ,q("q30","mcq","Which is a common element in an ArcMap map layout?","Scale bar",27,"The deck lists scale bars among map elements.",["Scale bar","Microwave transmitter","Leaf cell","Radiometer lens"])
 ,q("q31","tf","ArcMap maps are collections of layers.","true",27,"The ArcMap slide describes maps as layer collections.")
 ,q("q32","identify","The GIS company named Environmental Systems Research Institute is…","ESRI",29,"ESRI expands to Environmental Systems Research Institute.")
 ,q("q33","mcq","ESRI is headquartered in…","Redlands, California",29,"The source deck identifies Redlands, California.",["Redlands, California","Manila, Philippines","Paris, France","Tokyo, Japan"])
 ,q("q34","tf","GIS and remote sensing have the same role in the forest-cover example.","false",8,"Remote sensing captures imagery; GIS maps deforestation from it.")
 ,q("q35","classify","A device that records information from a distance without touching the target supports…","Remote sensing",4,"Non-contact acquisition is the core definition.")
 ,q("q36","identify","The radiation emitted as heat from objects can be detected by a…","Passive system",22,"Passive systems can detect emitted thermal radiation.")
 ,q("q37","tf","Remote sensing can be useful for politically inconvenient areas to access directly.","true",24,"The deck lists such locations among places RS can observe.")
 ,q("q38","mcq","What can change through time and limit a sensor's measurements?","Instrument calibration",25,"Instrument calibration drift is a stated limitation.",["Instrument calibration","Earth's existence","GIS layers","A map title"])
 ,q("q39","identify","The ArcGIS successor encouraged in the source deck is…","ArcGIS Pro",31,"The support-transition slide encourages moving to ArcGIS Pro.")
 ,q("q40","tf","Remote sensing data always gives direct, rather than indirect, environmental information.","false",18,"The deck says it can describe characteristics directly or indirectly.")
];

const pageNotes:string[]=[
 "GEn 411 Remote Sensing course cover.","Lesson 1 title: Introduction to Remote Sensing.","Introduction section transition.","Remote sensing definition: science and art of non-contact information acquisition.","Remote sensing definition emphasized: device does not contact object, area, or phenomenon.","Remote sensing versus GIS title visual.","Remote sensing as data source; GIS as analysis and visualization tool.","Remote sensing versus GIS explanation and forest-cover/deforestation example.","Definitions of remote sensing from general, ASPRS/Colwell, and James Campbell perspectives.","Restricted remote-sensing definition and airborne/spaceborne platforms.","Remote sensing commonly concerns EM techniques for Earth surface and atmosphere.","EMR examples and wavelike properties.","Human visual system as a remote-sensing-system example.","Scope of remote sensing and platforms.","Question: when to use remote sensing to obtain information.","Decision criteria: reliable, cost-effective, or new but necessary.","Question: is RS the best available information method?","Properties of remotely sensed data and non-interference.","Energy source: passive Sun and active lamps, lasers, microwave transmitters.","Energy interaction with object, reflection to sensor, quantization, and storage.","Stored values become images for processing and analysis.","Passive-system detection of reflected solar and emitted thermal radiation.","Active-system emitted radiation and atmospheric-transparency constraints.","Remote-sensing advantages.","Remote-sensing limitations.","Remote-sensing applications.","ArcMap familiarization and class-version/source-deck statement.","ArcMap maps, layers, and common map elements.","ArcMap and ESRI overview.","ESRI company and ArcGIS product family.","ESRI, ArcGIS platforms, and ArcMap support-transition statement.","Software-familiarization visual reference.","Software-familiarization visual reference.","Software-familiarization visual reference.","Software-familiarization visual reference.","Software-familiarization visual reference.","Software-familiarization visual reference.","Software-familiarization visual reference.","Software-familiarization visual reference.","Thank-you slide."
];
export const lesson1SourcePages:Lesson1SourcePage[]=pageNotes.map((extractedText,page)=>({page:page+1,module,extractedText,visualDescription:"Lesson 1 source slide reviewed and represented in the study content."}));
