import type { Concept, Difficulty, Question } from "./data";

export type Lesson5SourcePage = { page:number; module:string; extractedText:string; visualDescription:string };
const module = "Digital Image Processing";
const c = (id:string, term:string, definition:string, sourcePage:number, facts:string[] = [], difficulty:Difficulty = "medium"):Concept => ({ id:`l5-${id}`, module, topic:module, term, definition, facts, sourcePage, difficulty, tags:["Lesson 5", module, term] });
const q = (id:string, type:Question["type"], question:string, answer:string, sourcePage:number, explanation:string, choices?:string[], difficulty:Difficulty = "medium"):Question => ({ id:`l5-${id}`, type, question, answer, sourcePage, module, explanation, choices, difficulty });

export const lesson5Concepts:Concept[] = [
  c("digital-image","Digital image","A digital image is a two-dimensional array of picture elements arranged in fixed rows and columns.",3,["Each element records brightness for a location in the image."],"easy"),
  c("pixel","Pixel","A pixel is the smallest image element and represents the brightness at a particular image location.",4,["Pixel values are quantized numerical values."],"easy"),
  c("digital-number","Digital number (DN)","A digital number is the numerical brightness or intensity value assigned to a pixel.",6,["DNs can be added, subtracted, multiplied, divided, and statistically manipulated during processing."],"easy"),
  c("pixel-address","Pixel address","A pixel is identified by both its digital number and its row-and-column location address.",6,["The address locates the brightness value within the image array."],"medium"),
  c("scanning","Optical-mechanical scanning","Optical-mechanical scanners use mirrors and lenses to sweep a scene and convert varying land-surface brightness into an electrical signal.",7,["CCD and CMOS sensors collect photons and accumulate charge proportional to radiation intensity.","The resulting values are converted to digital numbers for each pixel."],"medium"),
  c("ccd-cmos","CCD and CMOS sensors","CCD and CMOS image sensors collect photons and create charge proportional to incoming radiance or intensity before conversion to digital numbers.",7,["They are solid-state detector technologies."],"medium"),
  c("ifov","Instantaneous field of view (IFOV)","IFOV is the smallest terrain area viewed by a sensor at one time and sets the lower limit of observable spatial detail.",8,["A smaller IFOV resolves finer ground detail."],"hard"),
  c("dwell-time","Dwell time","Dwell time is the interval during which a detector accumulates photons from the area within its IFOV.",8,["It must be sufficient to generate a strong signal.","It depends on altitude, platform speed, and detector sensitivity."],"hard"),
  c("bip","Band interleaved by pixel (BIP)","BIP storage writes all band values for one pixel before moving to the next pixel.",10,["It is organized pixel by pixel."],"medium"),
  c("bil","Band interleaved by line (BIL)","BIL storage writes values for every band along one line before writing the next line.",11,["It is organized scan line by scan line."],"medium"),
  c("bsq","Band sequential (BSQ)","BSQ storage writes an entire band separately before writing the next band.",12,["It is organized band by band."],"medium"),
  c("additive","Additive colour","Additive colour mixes blue, green, and red light; combining all three produces white.",13,["It underlies visual displays, the human eye, and colour photography."],"easy"),
  c("rgb","RGB components","RGB uses red, green, and blue channels to form a colour display from three image layers.",14,["Changing channel assignments changes the composite interpretation."],"easy"),
  c("subtractive","Subtractive colour","Subtractive colour uses cyan, magenta, and yellow primaries, especially in printing and painting.",15,["It works by absorbing portions of incident light."],"medium"),
  c("composite","Band composite","A colour composite assigns image bands to red, green, and blue display channels to make land-cover patterns easier to interpret.",17,["Different combinations emphasize different features."],"medium"),
  c("true-colour","True-colour composite","A Landsat true-colour composite assigns bands 3, 2, and 1 to red, green, and blue respectively.",18,["It approximates natural visual appearance."],"medium"),
  c("nir-composite","Near-infrared composite","A common near-infrared composite assigns Landsat bands 4, 3, and 2 to red, green, and blue.",18,["Healthy vegetation is commonly conspicuous in this false-colour view."],"medium"),
  c("swir-composite","Short-wave infrared composite","A common SWIR composite uses 7, 4, 2 or 7, 4, 3 in RGB order.",18,["It can support geological and moisture-related interpretation."],"hard"),
  c("band-choice","Band-combination selection","Band combinations are selected because different spectral bands improve identification of particular land-cover features.",19,["The most useful composite depends on the interpretation goal.","The lesson also shows Landsat TM assignments of RGB 321 and RGB 453."],"medium"),
  c("dip","Digital image processing (DIP)","DIP uses computer techniques to manipulate digital images, correct raw-data flaws, and extract useful information.",22,["Raw satellite-sensor data may contain flaws and deficiencies.","The approach depends on image format, initial condition, information needed, and scene composition."],"easy"),
  c("preprocessing","Pre-processing","Pre-processing removes systematic errors in raw image data before later analysis.",23,["It prepares data for reliable display, enhancement, and classification."],"medium"),
  c("enhancement","Display and enhancement","Display and enhancement operations improve image intelligibility for visual examination.",24,["They improve how patterns can be seen; they do not themselves assign classes."],"medium"),
  c("classification","Classification and information extraction","Classification and information extraction identify meaningful patterns and derive information from processed imagery.",24,["This is the analytical stage of the DIP workflow."],"medium"),
  c("brightness-value","Brightness / intensity value","A brightness or intensity value records the amount of image brightness represented at a specific pixel location.",4,["The value is quantized and represented digitally as a DN."],"easy"),
  c("image-arithmetic","Image-value operations","Digital brightness values can be added, subtracted, multiplied, divided, and statistically manipulated to support image analysis.",5,["Digital representation makes remotely sensed data easier to display, examine, and analyze."],"medium"),
  c("signal-chain","Photon-to-DN signal chain","Digital imaging converts scene brightness into an electrical signal, then sensor charge, and finally a digital number for each pixel.",7,["Moving mirrors or lenses support optical-mechanical scanning; CCD and CMOS are photon-collecting sensors."],"hard"),
  c("tm-assignments","Landsat TM RGB assignments","The lesson presents visible RGB = 321 and a second Landsat TM assignment of red = band 4, green = band 5, and blue = band 3.",20,["Keep the channel order explicit: the first number is red, the second green, and the third blue."],"medium"),
  c("raw-data","Raw image-data deficiencies","Raw data received from satellite imaging sensors can contain flaws and deficiencies, which is why processing is needed before extracting information.",22,["The required processing varies by image condition and intended information."],"medium"),
  c("processing-factors","Processing-selection factors","The appropriate digital processing depends on image format, the initial condition of the image, the information sought, and scene composition.",22,["There is no single processing workflow that is best for every image."],"hard"),
  c("dip-workflow","DIP workflow sequence","The lesson orders general digital image processing as pre-processing, display and enhancement, then classification and information extraction.",23,["The sequence moves from error correction to interpretation support to meaningful pattern extraction."],"easy"),
];

export const lesson5Questions:Question[] = [
  q("mcq-1","mcq","What is the smallest element of a digital image?","Pixel",4,"A pixel is the smallest image element.",["Pixel","Band","Scanner","Swath"],"easy"),
  q("mcq-2","mcq","What does a pixel's digital number represent?","Brightness or intensity",6,"A DN records pixel brightness or intensity.",["Brightness or intensity","Satellite altitude","Map scale","Cloud height"],"easy"),
  q("mcq-3","mcq","Which sensor technology collects photons before conversion to DNs?","CCD or CMOS",7,"CCD and CMOS sensors collect photons and generate proportional charge.",["CCD or CMOS","Compass","GPS receiver","Map legend"],"medium"),
  q("mcq-4","mcq","Which storage format records all bands for one pixel before the next pixel?","BIP",10,"Band interleaved by pixel is written pixel by pixel.",["BIP","BIL","BSQ","RGB"],"medium"),
  q("mcq-5","mcq","Which primary-colour set is additive?","Red, green, blue",13,"Additive colour mixes RGB light.",["Red, green, blue","Cyan, magenta, yellow","Red, yellow, black","Blue, cyan, yellow"],"easy"),
  q("mcq-6","mcq","Which process removes systematic errors from raw image data?","Pre-processing",23,"Pre-processing addresses systematic raw-data errors.",["Pre-processing","Classification","Subtractive mixing","Band compositing"],"medium"),
  q("mcq-7","mcq","Which stage identifies meaningful patterns in imagery?","Classification and information extraction",24,"Classification and extraction derive meaningful information.",["Classification and information extraction","Dwell time","BIP storage","IFOV"],"medium"),
  q("mcq-8","mcq","Which Landsat RGB combination is presented for a near-infrared composite?","432",18,"The lesson lists 432 as a near-infrared composite.",["432","321","111","654"],"hard"),
  q("identify-1","identify","The fixed row-and-column representation of picture elements is a…","Digital image",3,"A digital image is a 2D pixel array."),
  q("identify-2","identify","The numerical brightness assigned to a pixel is its…","Digital number",6,"A DN stores brightness or intensity."),
  q("identify-3","identify","The smallest terrain area a detector views at one moment is the…","IFOV",8,"IFOV defines the instantaneous area viewed."),
  q("identify-4","identify","The time a detector gathers photons from an IFOV is…","Dwell time",8,"Dwell time is the photon-accumulation interval."),
  q("identify-5","identify","The storage layout that writes all values for a line before the next line is…","BIL",11,"BIL is band interleaved by line."),
  q("identify-6","identify","The storage layout that holds each band separately is…","BSQ",12,"BSQ is band sequential."),
  q("identify-7","identify","Cyan, magenta, and yellow are the primaries of…","Subtractive colour",15,"CMY is used in subtractive colour systems."),
  q("identify-8","identify","Assigning bands to red, green, and blue display channels makes a…","Band composite",17,"An RGB assignment creates a colour composite."),
  q("tf-1","tf","A digital image has fixed rows and columns of pixels.","true",3,"The source defines digital images as fixed 2D arrays."),
  q("tf-2","tf","A pixel has brightness information but no location in the image.","false",6,"A pixel has both a DN and a row/column address."),
  q("tf-3","tf","IFOV establishes the lower limit of spatial detail a sensor can observe.","true",8,"The smallest area viewed limits spatial detail."),
  q("tf-4","tf","BIP stores every value for one band before writing the next band.","false",10,"That is BSQ; BIP groups bands by pixel."),
  q("tf-5","tf","Mixing red, green, and blue light produces white in an additive system.","true",13,"RGB light combines additively to white."),
  q("tf-6","tf","Subtractive colour is associated with printing and painting.","true",15,"CMY is used in subtractive media."),
  q("tf-7","tf","A true-colour Landsat composite uses RGB 432.","false",18,"The source lists true colour as RGB 321."),
  q("tf-8","tf","Image enhancement can improve visual intelligibility.","true",24,"Enhancement makes image content easier to examine."),
  q("number-1","number","A digital image is represented as a ___-dimensional array of pixels.","2",3,"The source describes a two-dimensional array."),
  q("number-2","number","How many primary channels are used in RGB additive colour?","3",13,"RGB has red, green, and blue channels."),
  q("number-3","number","In the true-colour Landsat combination, the red channel uses band ___.","3",18,"True colour is RGB 321."),
  q("number-4","number","In the near-infrared RGB 432 composite, the green channel uses band ___.","3",18,"RGB 432 assigns band 3 to green."),
  q("number-5","number","In RGB 321, the blue display channel uses band ___.","1",18,"True colour assigns band 1 to blue."),
  q("number-6","number","A BIP example in the lesson illustrates ___ image bands per pixel.","4",10,"The BIP storage diagram uses four bands."),
  q("number-7","number","The SWIR combination begins with band ___ in both listed examples.","7",18,"The listed SWIR composites are 742 and 743."),
  q("classify-1","classify","Classify BSQ as pixel, line, or band-oriented storage.","Band",12,"BSQ writes each band separately."),
  q("classify-2","classify","Classify a red-green-blue display system as additive or subtractive.","Additive",13,"RGB is an additive system."),
  q("classify-3","classify","Classify CMY printing inks as additive or subtractive.","Subtractive",15,"CMY is a subtractive system."),
  q("classify-4","classify","Classify removal of systematic sensor errors as pre-processing or classification.","Pre-processing",23,"Error removal occurs before analytical classification."),
  q("classify-5","classify","Classify recognition of meaningful land-cover patterns as enhancement or information extraction.","Information extraction",24,"The workflow identifies patterns during classification and extraction."),
  q("classify-6","classify","Classify an image layout that completes all band values along one scan line before the next line.","BIL",11,"This is the defining BIL order."),
  q("classify-7","classify","Classify an RGB 321 Landsat view as true colour or near-infrared false colour.","True colour",18,"RGB 321 approximates natural visible colour."),
  q("classify-8","classify","Classify an RGB 742 Landsat display by its emphasized spectral region.","Short-wave infrared",18,"The source lists 742 as a SWIR composite."),
  q("classify-9","classify","Classify the use of computer techniques to manipulate a digital image.","Digital image processing",22,"DIP is the computer-based manipulation of digital images."),
  q("review-mcq-operations","mcq","Which operation can be applied to digital brightness values during image processing?","Multiplication",5,"The reviewer notes that digital brightness values can be added, subtracted, multiplied, divided, and statistically manipulated.",["Multiplication","Only drawing","Only printing","Only orbiting"],"medium"),
  q("review-tf-raw-data","tf","Raw data from satellite imaging sensors may need processing because it can contain flaws and deficiencies.","true",22,"DIP improves the usability of imperfect raw sensor data."),
  q("review-identify-signal-chain","identify","The conversion from scene brightness through electrical signal and sensor charge into a per-pixel DN is the…","Photon-to-DN signal chain",7,"The sensor pathway ends with a digital number for each pixel."),
  q("review-mcq-tm","mcq","Which Landsat TM channel assignment is shown as the second example in the lesson?","Red 4, green 5, blue 3",20,"The source presents RGB 453 as a Landsat TM assignment.",["Red 4, green 5, blue 3","Red 1, green 2, blue 3","Red 7, green 4, blue 2","Red 2, green 3, blue 4"],"hard"),
  q("review-classify-factors","classify","Classify image format, initial image condition, needed information, and scene composition.","Processing-selection factors",22,"These determine the appropriate digital processing approach."),
  q("boss-1","boss","Boss: You need the original brightness value and the exact image location of a target. Which pair provides both?","Digital number and row-column address",6,"A pixel combines its DN with a row/column address.",["Digital number and row-column address","IFOV and swath","RGB and CMY","Mirror and lens"],"hard"),
  q("boss-2","boss","Boss: Which data-order choice is correct for a workflow analyzing one entire spectral band at a time?","BSQ",12,"BSQ keeps one whole band together.",["BSQ","BIP","BIL","RGB"],"hard"),
  q("boss-3","boss","Boss: An analyst needs to make weak patterns easier to see before assigning classes. What should happen next?","Display and enhancement",24,"Enhancement improves intelligibility before classification.",["Display and enhancement","Subtractive colour","Dwell time","Pixel addressing"],"hard"),
  q("boss-4","boss","Boss: What workflow order is presented for digital image processing?","Pre-processing, display and enhancement, classification and information extraction",23,"The deck presents these three major stages in this order.",["Pre-processing, display and enhancement, classification and information extraction","Classification, BIP storage, IFOV","RGB mixing, pixel addressing, scanning","Enhancement, sensor launch, georeferencing"],"expert"),
];

const sourceNotes = [
  "GEn 411 Remote Sensing course cover.","Lesson 5: Digital Image Processing.","Digital image representation as a two-dimensional array of pixels.","Pixels are the smallest image elements with quantized brightness values.","Digital values support mathematical and statistical image manipulation.","Each pixel has a digital number plus a row-and-column address.","Optical-mechanical scanning, CCD, and CMOS conversion of radiance to DNs.","IFOV and dwell time define sensed area and photon accumulation.","Multiband image storage: BIP, BIL, and BSQ.","BIP writes all bands for one pixel before the next pixel.","BIL writes all bands for one line before the next line.","BSQ writes one complete band before the next band.","Additive RGB colour mixing.","RGB components and display channels.","Subtractive CMY colour mixing.","RGB component illustration.","RGB band composite examples.","True-colour 321, NIR 432, and SWIR 742/743 composites.","Some bands identify land-cover features better than others.","Landsat TM 321 and 453 composite assignments.","Landsat composite visual example.","Digital image processing definition and scope.","DIP workflow: pre-processing, enhancement, classification/extraction.","Functions of the three DIP workflow stages.","Closing slide."
];
export const lesson5SourcePages:Lesson5SourcePage[] = sourceNotes.map((extractedText, page) => ({ page:page + 1, module, extractedText, visualDescription:"Source slide reviewed." }));
