import "./style.css";
import { concepts, extendedConcepts, extendedQuestions, masteryConcepts, masteryQuestions, modules, pdfCoverage, questions, supplementalConcepts, supplementalQuestions, type Concept, type Question } from "./data";
import { pdfSourcePages } from "./pdf-source";
type State={xp:number; streak:number; mastered:Record<string,number>; due:Record<string,number>; history:string[]; errors:string[]};
const key="remote-sensing-quest-v1";
const state:State=JSON.parse(localStorage.getItem(key)||'{"xp":0,"streak":1,"mastered":{},"due":{},"history":[],"errors":[]}');
const save=()=>localStorage.setItem(key,JSON.stringify(state));
const esc=(s:string)=>s.replace(/[&<>"']/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[x]!));
const moduleFor=(name:string)=>modules.find(m=>m.name===name)!;
const mastery=(c:Concept)=>state.mastered[c.id]||0;
const level=()=>Math.floor(state.xp/150)+1;
const studyConcepts=[...concepts,...extendedConcepts,...supplementalConcepts,...masteryConcepts];
const allQuestions=[...questions,...extendedQuestions,...supplementalQuestions,...masteryQuestions];
const flashcards=studyConcepts;
let view:"home"|"learn"|"cover"|"flash"|"quiz"|"library"|"source"="home";
let active=0; let quizIndex=0; let score=0; let mode="mcq"; let revealed=false;
function nav(){return `<aside><div class="brand">◉ ORBIT<br><small>STUDY QUEST</small></div>${[["home","⌂ Dashboard"],["learn","◈ Learn"],["cover","◐ Cover & Check"],["flash","▣ Flashcards"],["quiz","⚔ Challenge"],["library","⌕ Study Library"],["source","▦ Lesson Notes"]].map(([id,label])=>`<button class="nav ${view===id?"active":""}" data-view="${id}">${label}</button>`).join("")}<div class="side-note">Remote sensing study guide<br><b>104 lesson pages</b></div></aside>`}
function progress(c:Concept){return `<div class="dots">${[1,2,3,4,5].map(n=>`<i class="${mastery(c)>=n?"on":""}"></i>`).join("")}</div>`}
function home(){const master=studyConcepts.filter(c=>mastery(c)>=5).length; const coverage=Math.round(pdfCoverage.filter(p=>p.processed).length/104*100); return `<main><header><div><p class="eyebrow">WELCOME BACK, EXPLORER</p><h1>Map the unseen.</h1><p class="muted">Master sensors, platforms, imagery and Earth observation systems.</p></div><div class="level">LVL ${level()}<span>${state.xp} XP</span></div></header><section class="stats"><article><span>⚡</span><b>${state.xp}</b><small>XP earned</small></article><article><span>🔥</span><b>${state.streak}</b><small>day streak</small></article><article><span>◎</span><b>${master}/${studyConcepts.length}</b><small>mastered concepts</small></article><article><span>▦</span><b>${coverage}%</b><small>PDF coverage</small></article></section><section class="hero"><div><p class="eyebrow">TODAY'S MISSION</p><h2>${flashcards.filter(c=>(state.due[c.id]||0)<=Date.now()).length||3} reviews due</h2><p>Build recall with spaced repetition, then test your knowledge in a mixed challenge.</p><button data-action="start-cover">Begin cover & check →</button></div><div class="planet">◌<small>EARTH OBSERVATION</small></div></section><h2>Learning path</h2><div class="modules">${modules.map((m,i)=>{const cs=studyConcepts.filter(c=>c.module===m.name);const pct=cs.length?Math.round(cs.reduce((n,c)=>n+mastery(c),0)/(cs.length*5)*100):0;return `<article class="module"><span>0${i+1}</span><h3>${esc(m.name)}</h3><p>Pages ${m.pages[0]}–${m.pages[1]} · ${cs.length} concepts</p><div class="bar"><i style="width:${pct}%"></i></div><small>${pct}% mastery</small></article>`}).join("")}</div></main>`}
function learn(){const c=studyConcepts[active%studyConcepts.length]; return `<main><header><div><p class="eyebrow">LEARN · PAGE ${c.sourcePage}</p><h1>${esc(c.term)}</h1><p class="muted">${esc(c.topic)}</p></div>${progress(c)}</header><section class="study-card"><p class="definition">${esc(c.definition)}</p><div class="fact-list">${c.facts.map(f=>`<p>✦ ${esc(f)}</p>`).join("")}</div><footer><span>Source: PDF page ${c.sourcePage}</span><div><button class="ghost" data-action="prev">← Previous</button><button data-action="next">Next concept →</button></div></footer></section><section><h2>More in this module</h2><div class="chips">${studyConcepts.filter(x=>x.module===c.module).map(x=>`<button data-concept="${x.id}">${esc(x.term)}</button>`).join("")}</div></section></main>`}
function cover(){const c=flashcards[active%flashcards.length];return `<main><header><div><p class="eyebrow">COVER & CHECK · PAGE ${c.sourcePage}</p><h1>Recall before you reveal.</h1></div>${progress(c)}</header><section class="cover-card"><p>${esc(c.definition)}</p>${revealed?`<div class="answer">${esc(c.term)}<small>${c.facts[0]?esc(c.facts[0]):"PDF-grounded concept"}</small></div><h3>Did you remember it?</h3><div class="rating"><button data-rate="1">Again</button><button data-rate="3">Almost</button><button data-rate="5">Yes — easy</button></div>`:`<button class="reveal" data-action="reveal">Reveal answer</button>`}<small>Source: PDF page ${c.sourcePage}</small></section></main>`}
function flash(){const c=flashcards[active%flashcards.length]; return `<main><header><div><p class="eyebrow">SPACED REPETITION</p><h1>Flashcards</h1></div><span class="badge">${Object.values(state.due).filter(d=>d<=Date.now()).length} due</span></header><section class="flash"><button class="card-face ${revealed?"back":""}" data-flashcard aria-label="Flip flashcard. You can also press Space or Enter."><small>${revealed?"ANSWER":"TERM"}</small><h2>${esc(revealed?c.definition:c.term)}</h2>${revealed?`<p>${c.facts.map(esc).join(" · ")}</p><em>PDF page ${c.sourcePage}</em>`:`<em>Tap the card, or press Space / Enter to flip</em>`}</button>${revealed?`<div class="rating"><button data-rate="1">Again</button><button data-rate="2">Hard</button><button data-rate="4">Good</button><button data-rate="5">Easy</button></div>`:`<button class="reveal" data-action="reveal">Flip card</button>`}</section></main>`}
function questionSet(){const filtered=mode==="boss"?allQuestions:allQuestions.filter(q=>mode==="mixed"||q.type===mode);return filtered.length?filtered:allQuestions}
function quiz(){const qs=questionSet();const q=qs[quizIndex%qs.length];const boss=mode==="boss";return `<main><header><div><p class="eyebrow">${boss?"BOSS BATTLE":"CHALLENGE"} · ${q.difficulty.toUpperCase()}</p><h1>${boss?"🛰 SENSOR COMMANDER":"Test your signal"}</h1><p class="muted">Question ${(quizIndex%qs.length)+1} of ${qs.length} · Score ${score}</p></div>${boss?`<div class="health"><span style="width:${Math.max(0,100-score*5)}%"></span></div>`:""}</header><div class="mode-row">${[["mixed","Mixed"],["mcq","Multiple choice"],["identify","Identification"],["tf","True / false"],["number","Numbers"],["classify","Classification"],["boss","Boss battle"]].map(([id,l])=>`<button class="${mode===id?"selected":""}" data-mode="${id}">${l}</button>`).join("")}</div><section class="quiz-card"><small>PDF PAGE ${q.sourcePage} · ${esc(q.module)}</small><h2>${esc(q.question)}</h2>${q.choices?`<div class="choices">${q.choices.map(x=>`<button data-answer="${esc(x)}">${esc(x)}</button>`).join("")}</div>`:q.type==="tf"?`<div class="choices"><button data-answer="true">True</button><button data-answer="false">False</button></div>`:`<form id="answer-form"><input autofocus placeholder="Type your answer"/><button>Check answer</button></form>`}<div id="feedback"></div></section></main>`}
function library(){return `<main><header><div><p class="eyebrow">SEARCHABLE STUDY ENCYCLOPEDIA</p><h1>Study library</h1><p class="muted">Every entry retains its PDF source page.</p></div></header><input id="search" class="search" placeholder="Search sensors, satellites, resolution, bands…"/><div id="library-list" class="library">${conceptList(studyConcepts)}</div></main>`}
function conceptList(list:Concept[]){return list.map(c=>`<article><small>${esc(c.module)} · PDF ${c.sourcePage}</small><h3>${esc(c.term)}</h3><p>${esc(c.definition)}</p>${progress(c)}</article>`).join("")||"<p>No matching concepts.</p>"}
function source(){return `<main><header><div><p class="eyebrow">LESSON REFERENCE</p><h1>All 104 lesson pages</h1><p class="muted">Search terms, values, diagrams, tables and satellite specifications from the lesson.</p></div></header><input id="source-search" class="search" placeholder="Search lesson terms, values, satellite names…"/><div id="source-list" class="source-list">${sourceList(pdfSourcePages)}</div></main>`}
function sourceList(items:typeof pdfSourcePages){return items.map(p=>`<article><header><b>PDF PAGE ${p.page}</b><span>${esc(pdfCoverage[p.page-1].module)}</span></header><p class="visual-note">Page note: ${esc(p.visualDescription)}</p><pre>${esc(p.extractedText||"This page is represented by a diagram, figure, or table.")}</pre></article>`).join("")||"<p>No matching lesson page.</p>"}
function render(){document.querySelector<HTMLDivElement>("#app")!.innerHTML=nav()+(view==="home"?home():view==="learn"?learn():view==="cover"?cover():view==="flash"?flash():view==="quiz"?quiz():view==="library"?library():source());bind();bindFlashFlip()}
function bindFlashFlip(){document.querySelector("[data-flashcard]")?.addEventListener("click",()=>{revealed=!revealed;render()});document.onkeydown=(event)=>{if(view!=="flash"||event.key!==" "&&event.key!=="Enter")return;const target=event.target as HTMLElement;if(target.tagName==="INPUT"||target.tagName==="BUTTON")return;event.preventDefault();revealed=!revealed;render()}}
function advance(){active=(active+1)%studyConcepts.length;revealed=false;render()}
function rate(n:number){const c=flashcards[active%flashcards.length];state.mastered[c.id]=Math.max(0,Math.min(5,(state.mastered[c.id]||0)+(n>=4?1:n===1?-1:0))); state.xp+=n>=4?15:5;state.due[c.id]=Date.now()+([0,1,3,7,14,30][n]||1)*86400000;save();advance()}
function answer(value:string){const q=questionSet()[quizIndex%questionSet().length];const clean=(x:string)=>x.trim().toLowerCase().replace(/[^a-z0-9]/g,"");const ok=clean(value)===clean(q.answer)||clean(q.answer).includes(clean(value))&&clean(value).length>2;const feedback=document.querySelector("#feedback")!; feedback.innerHTML=`<div class="feedback ${ok?"ok":"no"}"><b>${ok?"Correct! +15 XP":"Not quite."}</b><p>${esc(q.explanation)} Source: PDF page ${q.sourcePage}.</p><button data-action="next-q">Next question →</button></div>`;if(ok){score++;state.xp+=15}else state.errors.push(q.id);state.history.push(q.id);save();document.querySelectorAll("[data-answer]").forEach(b=>(b as HTMLButtonElement).disabled=true)}
function bind(){document.querySelectorAll("[data-view]").forEach(b=>b.addEventListener("click",()=>{view=(b as HTMLElement).dataset.view as typeof view;revealed=false;render()}));document.querySelectorAll("[data-action]").forEach(b=>b.addEventListener("click",()=>{const a=(b as HTMLElement).dataset.action;if(a==="next"||a==="start-cover") {if(a==="start-cover")view="cover";else active++;revealed=false;render()} if(a==="prev"){active=(active-1+studyConcepts.length)%studyConcepts.length;render()}if(a==="reveal"){revealed=true;render()}if(a==="next-q"){quizIndex++;render()}}));document.querySelectorAll("[data-rate]").forEach(b=>b.addEventListener("click",()=>rate(Number((b as HTMLElement).dataset.rate))));document.querySelectorAll("[data-concept]").forEach(b=>b.addEventListener("click",()=>{active=studyConcepts.findIndex(c=>c.id===(b as HTMLElement).dataset.concept);render()}));document.querySelectorAll("[data-mode]").forEach(b=>b.addEventListener("click",()=>{mode=(b as HTMLElement).dataset.mode!;quizIndex=0;score=0;render()}));document.querySelectorAll("[data-answer]").forEach(b=>b.addEventListener("click",()=>answer((b as HTMLElement).dataset.answer!)));document.querySelector("#answer-form")?.addEventListener("submit",e=>{e.preventDefault();answer((new FormData(e.currentTarget as HTMLFormElement).get("")||document.querySelector<HTMLInputElement>("#answer-form input")!.value).toString())});document.querySelector("#search")?.addEventListener("input",e=>{const value=(e.target as HTMLInputElement).value.toLowerCase();document.querySelector("#library-list")!.innerHTML=conceptList(studyConcepts.filter(c=>`${c.term} ${c.definition} ${c.module} ${c.facts.join(" ")}`.toLowerCase().includes(value)))});document.querySelector("#source-search")?.addEventListener("input",e=>{const value=(e.target as HTMLInputElement).value.toLowerCase();document.querySelector("#source-list")!.innerHTML=sourceList(pdfSourcePages.filter(p=>`${p.page} ${p.extractedText} ${p.visualDescription}`.toLowerCase().includes(value)))});
}
render();
